# Generated by Django 4.2.27 on 2026-05-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.IntegerField(default=0, verbose_name='申請單id')),
                ('created', models.DateField(auto_now_add=True, verbose_name='表單建立時間')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(default=0, verbose_name='社團id')),
                ('club_name', models.CharField(max_length=64, verbose_name='社團名稱')),
                ('max_people_num', models.IntegerField(default=0, verbose_name='社團人數上限')),
                ('now_people_num', models.IntegerField(default=0, verbose_name='社團現有人數')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_id', models.IntegerField(default=0, verbose_name='使用者編號')),
                ('us_name', models.CharField(max_length=64, verbose_name='使用者姓名')),
                ('us_email', models.CharField(max_length=128, verbose_name='使用者信箱')),
                ('us_rank', models.IntegerField(default=0, verbose_name='使用者身分')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.IntegerField(default=0, verbose_name='歷史路徑id')),
                ('result', models.BooleanField(default=False, verbose_name='審查結果')),
                ('date', models.DateField(auto_now_add=True, verbose_name='審核時間')),
                ('state', models.IntegerField(default=0, verbose_name='目前審核狀態')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.apply')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.user')),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
        migrations.AddField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.user'),
        ),
    ]
