# Generated by Django 4.2.27 on 2026-05-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='ap_id',
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='log',
            name='path_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='us_id',
        ),
    ]
