# Generated by Django 4.2.27 on 2026-05-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_apply_ap_id_remove_club_club_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club',
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.user'),
            preserve_default=False,
        ),
    ]
