# Generated by Django 4.2.27 on 2026-05-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_remove_club_user_user_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='sch_pass',
            field=models.BooleanField(default=False, verbose_name='學校同意'),
        ),
        migrations.AddField(
            model_name='apply',
            name='sstu_pass',
            field=models.BooleanField(default=False, verbose_name='社長同意'),
        ),
    ]
