# Generated by Django 4.2.27 on 2026-05-21 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_apply_sch_pass_apply_sstu_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='now_people_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(512)], verbose_name='社團現有人數'),
        ),
    ]
