# Generated by Django 4.2.27 on 2026-05-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_club_now_people_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='club_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after_apply', to='club.club'),
        ),
    ]
